name: get_xproject
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  url_strategy: 0.2.0
  flutter: 
    sdk: flutter
  dio: ^4.0.0
  webview_flutter: ^4.2.0
  quick_actions: ^1.0.3
  fluttertoast: ^8.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
    
  flutter_ume: ^1.0.1
  flutter_ume_kit_ui: ^1.0.0
  flutter_ume_kit_device: ^1.0.0
  flutter_ume_kit_perf: ^1.0.0
  flutter_ume_kit_show_code: ^1.0.0
  flutter_ume_kit_console: ^1.0.0
  flutter_ume_kit_dio: ^1.0.1

flutter: 
  uses-material-design: true
  assets:
    - images/icon.png
    - assets/icon_1.png
    - assets/icon_2.png

# build:
#     web:
#       options:
#         --dart-define=FLUTTER_BASE_HREF=/debugFlutter/


